export const CareerOptions = [

    "AI/Machine Learning Engineer",
    "AI/Machine Learning Scientist",
    "AI Product Manager",
    "AI Research Scientist",
    "AI Solutions Architect",
    "AI/Blockchain/Data Solutions Consultant",
    "Big Data Engineer",
    "Blockchain Architect",
    "Blockchain Consultant",
    "Blockchain Developer",
    "Blockchain Product Manager",
    "Blockchain Security Engineer",
    "Business Development / Sales Manager",
    "Business Intelligence (BI) Analyst",
    "Cloud Engineer",
    "Compliance Officer",
    "Computer Vision Engineer",
    "Cryptography Engineer",
    "Data Analyst",
    "Data Architect",
    "Data Engineer",
    "Data Labeling Specialist",
    "Data Scientist",
    "Data Security Specialist",
    "Data Visualization Specialist",
    "Database Administrator",
    "Decentralized Application (dApp) Developer",
    "Deep Learning Engineer",
    "DevOps Engineer",
    "Director of AI Solutions",
    "Director of Blockchain Solutions",
    "Director of Data Solutions",
    "Head of Data Science",
    "HR Manager",
    "Legal Counsel",
    "Marketing Manager",
    "Natural Language Processing (NLP) Engineer",
    "Product Marketing Manager",
    "Project Manager",
    "QA Engineer",
    "Sales Director",
    "Smart Contract Developer",
    "Software Engineer (Backend/Frontend/Full-Stack)",
    "Systems Architect",
    "Technical Presales Engineer",
    "Technical Support Engineer",
    "Technical Writer",
    "UI/UX Designer",
    "VP of Engineering",
    "VP of Product"
]


export const locationPreferences  = [
    'USA','UAE','Saudi Arabia','India','Other'
]
